import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Crimson_Pro } from 'next/font/google';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const crimsonPro = Crimson_Pro({
  subsets: ['latin'],
  variable: '--font-crimson-pro',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${crimsonPro.variable} antialiased`}>
        {/* NAVBAR */}
        <div className="navbar bg-base-100 shadow-sm bg-navbar flex items-center">
          {/* Logo */}
          <div>
            <Link href="/" className="btn btn-ghost text-xl">LOGO</Link>
          </div>

          {/* Links centrados */}
          <div className="flex-1 flex justify-center">
            <ul className="menu menu-horizontal text-xl px-1 gap-x-12">
              <li><Link href="/about">About us</Link></li>
              <li><Link href="/servicios">Services</Link></li>
              <li><Link href="/clients">Clients</Link></li>
              <li><Link href="/contact">Contact</Link></li>
            </ul>
          </div>

          {/* Botón alineado a la derecha */}
          <div className="flex-none pr-4">
            <button
              className="btn rounded-full w-[160px]"
              style={{ backgroundColor: '#69B578', borderColor: '#69B578', color: 'white' }}
            >
              Learn more
            </button>
          </div>
        </div>
        {/* CONTENIDO DE LA PÁGINA */}
        <main>{children}</main>

      </body>
    </html>
  );
}
